### ISSUE TITLE
Failed to validate /Applications/Utilities/Notifier.app/Contents/Resources/alert/Notifier - Alerts.app for use with identifier uk.co.dataJAR.NotifierAlerts (pid: 2959)

### ISSUE THREAD

**Issue by svinusje** [dataJAR/Notifier#14]
in the verbose log i get this error message:

Failed to validate /Applications/Utilities/Notifier.app/Contents/Resources/alert/Notifier - Alerts.app for use with identifier uk.co.dataJAR.NotifierAlerts (pid: 2959)

i have the notification profile in place, suggestions what i can try? This is on a 11.3.1 device

![Screenshot 2021-05-19 at 11 21 02](https://user-images.githubusercontent.com/57441837/118789179-cda8e280-b894-11eb-8352-e19a35ffcc17.png)

**Comment by macmule** [comment]
@svinusje have you resigned the app or modified it in anyway?

**Comment by svinusje** [comment]
no i use the default pkg

**Comment by macmule** [comment]
@svinusje is this still an issue?

**Comment by dom404** [comment]
> @svinusje is this still an issue?

Worked perfectly for me. Amazing work

**Comment by macmule** [comment]
Closing this off as cannot recreate, sorry!
