### ISSUE TITLE
Close button missing on macOS 10.15 for alert notification

### ISSUE THREAD

**Issue by redshirtdave** [dataJAR/Notifier#3]
Calling notifier with alert type notification has a different visual result on two tested OSes. Using the following example:

`notifier --type alert --title "Company" --subtitle "Communication" --message "macOS Big Sur" --messagebutton "Info" --messagebuttonaction "https://www.apple.com/macos/big-sur-preview/"`

macOS 10.13.6 - Shows a Close and Info (action) button.
macOS 10.15.6 - Shows only the Info (action) button.

**Comment by macmule** [comment]
Looks like a 10.15.6 change, on 10.15.5:

<img width="382" alt="Screenshot 2020-07-28 09 46 45" src="https://user-images.githubusercontent.com/2464974/88641593-57de4b00-d0b7-11ea-8cec-b49cee51176b.png">

**Comment by macmule** [comment]
Had someone test on 10.15.6 too:

<img width="382" alt="Screenshot 2020-07-28 at 09 55 56" src="https://user-images.githubusercontent.com/2464974/88642681-b35d0880-d0b8-11ea-8340-82dd7e062b8b.png">

If you've changed the bundle identifier of the apps, you'll need to amend the pushed profile.

If you've not changed the bundle identifier, but haven't pushed the profile. Push the profile then try again :)

**Comment by redshirtdave** [comment]
Scrap that, error on my part. My config profile was forcing 'Banners' as the alert style, not 'Alerts' as it should be. So the effect of that 'Banners' setting leaves the action button in place and removes the close button.
