### ISSUE TITLE
ERROR: Notification Center is not running..

### ISSUE THREAD

**Issue by GenoMyb** [dataJAR/Notifier#4]
./Notifier --type alert --message "Please Logout" --messagebutton "Logout" --title "Logout"
ERROR: Notification Center is not running...
admins-MacBook-Pro:MacOS admin$

**Comment by macmule** [comment]
more details?

Which OS? ssh'd in?

**Comment by GenoMyb** [comment]
Hi MacMule 

macOS 10.16 Beta 3 
running from terminal

**Comment by macmule** [comment]
can you post the output of the below?

`sw_vers`

**Comment by GenoMyb** [comment]
ProductName:	macOS
ProductVersion:	11.0
BuildVersion:	20A5323l

**Comment by macmule** [comment]
Looks like Apple have changed the OS version report via the method used below:

https://github.com/dataJAR/Notifier/blob/master/Notifier/Notifier/AppDelegate.swift#L26-L37

Will need to amend & test. Thanks for pointing this out.

**Comment by GenoMyb** [comment]
Thank you MacMule 
Thank you for making this available

**Comment by macmule** [comment]
@GenoMyb should be sorted now with 2.2.1.. any issues please re-open this.

**Comment by GenoMyb** [comment]
Thanks , will test
